Repository FaculdadeSenaiJoinville/odyssey-dictionary, pull requests merged in 2021-11, with the labels that each got.

#39 PES-346 - Validação que no nome tenha pelo menos um espaço para obrigar a colocar nome e sobrenome
  package.json
  src/core/misc.ts
  src/translations/index.ts
  src/translations/modules/system-errors.translation.ts
  src/translations/modules/users.translation.ts
Labels: bug, code review

#40 Modal de detalhes de grupos
  package.json
  src/translations/modules/groups.translation.ts
Labels: code review, feature

#41 PES-342 - Tela de login está fazendo uma requisição para "/me"
  package.json
  src/translations/modules/system-errors.translation.ts
Labels: bug, code review

#43 PES-354 - Criar bot do telegram
  package.json
  src/core/misc.ts
  src/index.ts
  src/translations/index.ts
  src/translations/modules/chatbot.translation.ts
Labels: feature

#44 PES-313 - Modal de excluir grupos
  package.json
  src/translations/modules/groups.translation.ts
Labels: code review, feature

#45 PES-351 - Desenvolvimento Telas
  package.json
  src/translations/modules/bot_contents.translation.ts
  src/translations/modules/bot_intents.translation.ts
Labels: code review, feature

#46 PES-355 - Histórico do chatbot
  package.json
  src/core/misc.ts
  src/index.ts
  src/translations/index.ts
  src/translations/modules/bot_histories.translation.ts
Labels: code review, feature
